controller_manager:
  ros__parameters:
     enable_read_statistics: false
     enable_write_statistics: false
     update_rate: 1000
     use_sim_time : true

    # Publish all joint states -----------------------------------
     joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 100

     joint_group_position_controller:
      ros__parameters:
       type: position_controllers/JointGroupPositionController
       publish_rate: 100
       joints:
        - FL_hip_joint
        - FL_thigh_joint
        - FL_calf_joint
        - FR_hip_joint
        - FR_thigh_joint
        - FR_calf_joint
        - RL_hip_joint
        - RL_thigh_joint
        - RL_calf_joint
        - RR_hip_joint
        - RR_thigh_joint
        - RR_calf_joint
       Command_interfaces:
        - position
       state_interfaces:
        - position
        - velocity

     
      

    # FL Controllers ---------------------------------------
     FL_hip_controller:
        type: position_controllers/JointPositionController
        joint: FL_hip_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

     FL_thigh_controller:
        type: position_controllers/JointPositionController
        joint: FL_thigh_joint
        pid: {p: 100.0, i: 0.0, d: 8.0}

     FL_calf_controller:
        type: position_controllers/JointPositionController
        joint: FL_calf_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    # FR Controllers ---------------------------------------
     FR_hip_controller:
        type: position_controllers/JointPositionController
        joint: FR_hip_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

     FR_thigh_controller:
        type: position_controllers/JointPositionController
        joint: FR_thigh_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

     FR_calf_controller:
        type: position_controllers/JointPositionController
        joint: FR_calf_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    # RL Controllers ---------------------------------------
     RL_hip_controller:
        type: position_controllers/JointPositionController
        joint: RL_hip_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

     RL_thigh_controller:
        type: position_controllers/JointPositionController
        joint: RL_thigh_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

     RL_calf_controller:
        type: position_controllers/JointPositionController
        joint: RL_calf_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    # RR Controllers ---------------------------------------
     RR_hip_controller:
        type: position_controllers/JointPositionController
        joint: RR_hip_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

     RR_thigh_controller:
        type: position_controllers/JointPositionController
        joint: RR_thigh_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

     RR_calf_controller:
        type: position_controllers/JointPositionController
        joint: RR_calf_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}
