controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

joint_group_position_controller:
  ros__parameters:
    use_sim_time: true
    joints:
        - FL_hip_joint
        - FL_thigh_joint
        - FL_calf_joint
        - FR_hip_joint
        - FR_thigh_joint
        - FR_calf_joint
        - RL_hip_joint
        - RL_thigh_joint
        - RL_calf_joint
        - RR_hip_joint
        - RR_thigh_joint
        - RR_calf_joint 
    
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    
    allow_partial_joints_goal: true
    
    # Important settings for controller stability
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      
    # Default settings that can help with stability
    hold_trajectory_duration: 0.0
    action_tolerance: 1.0


    gains:
       FL_hip_joint:   {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       FL_thigh_joint: {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       FL_calf_joint:  {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       FR_hip_joint:   {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       FR_thigh_joint: {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       FR_calf_joint:  {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       RL_hip_joint:   {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       RL_thigh_joint: {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       RL_calf_joint:  {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       RR_hip_joint:   {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       RR_thigh_joint: {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}
       RR_calf_joint:  {p: 100.0, i: 0.2, d: 1.0, antiwindup: integrator_clamp, i_clamp: 2.5}





















    
    #gains:
     # FL_hip_joint        : {p: 100.0, i: 0.0, d: 5.0}
     # FL_thigh_joint      : {p: 100.0, i: 0.0, d: 1.0}
     # FL_calf_joint       : {p: 300.0, i: 0.0, d: 1.0}
      #FR_hip_joint        : {p: 100.0, i: 0.0, d: 5.0}
      #FR_thigh_joint      : {p: 100.0, i: 0.0, d: 1.0}
      #FR_calf_joint       : {p: 300.0, i: 0.0, d: 1.0}
      #RL_hip_joint        : {p: 100.0, i: 0.0, d: 5.0}
      #RL_thigh_joint      : {p: 100.0, i: 0.0, d: 1.0}
      #RL_calf_joint       : {p: 300.0, i: 0.0, d: 1.0}
      #RR_hip_joint        : {p: 100.0, i: 0.0, d: 5.0}
      #RR_thigh_joint      : {p: 100.0, i: 0.0, d: 1.0}
      #RR_calf_joint       : {p: 300.0, i: 0.0, d: 1.0}
      # {p: 67.5, d: 0.3, i: 0.1, i_clamp: 1.5}
    # action_monitor_rate: 10.0 # Defaults to 20
    # state_publish_rate: 10.0 # Defaults to 50
    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

# joint_group_position_controller:
#   ros__parameters:
#     use_sim_time: True
#     type: joint_trajectory_controller/JointTrajectoryController
#     joints:
#         - lf_hip_joint
#         - lf_thigh_joint
#         - lf_calf_joint
#         - rf_hip_joint
#         - rf_thigh_joint
#         - rf_calf_joint
#         - lh_hip_joint
#         - lh_thigh_joint
#         - lh_calf_joint
#         - rh_hip_joint
#         - rh_thigh_joint
#         - rh_calf_joint 
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
    
#     # state_publish_rate: 25.0 # Defaults to 50
#     # action_monitor_rate: 10.0 # Defaults to 20
#     open_loop_control: true
#     allow_integration_in_goal_trajectories: true
#     constraints:
#       stopped_velocity_tolerance: 0.01 # Defaults to 0.01
#       goal_time: 0.0 # Defaults to 0.0 (start immediately)
    # gains:
    #     lf_hip_joint        : {p: 180, d: 0.9, i: 20}
    #     lf_thigh_joint  : {p: 180, d: 0.9, i: 20}
    #     lf_calf_joint  : {p: 180, d: 0.9, i: 20}
    #     rf_hip_joint        : {p: 180, d: 0.9, i: 20}
    #     rf_thigh_joint  : {p: 180, d: 0.9, i: 20}
    #     rf_calf_joint  : {p: 180, d: 0.9, i: 20}
    #     lh_hip_joint        : {p: 180, d: 0.9, i: 20}
    #     lh_thigh_joint  : {p: 180, d: 0.9, i: 20}
    #     lh_calf_joint  : {p: 180, d: 0.9, i: 20}
    #     rh_hip_joint        : {p: 180, d: 0.9, i: 20}
    #     rh_thigh_joint  : {p: 180, d: 0.9, i: 20}
    #     rh_calf_joint  : {p: 180, d: 0.9, i: 20}
